[tool.poetry]
name = "fma-prep"
version = "0.1.5"
description = ""
authors = ["sette <bruno.sette@ufscar.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<=3.11.9"
pandas = "1.5.3"
numpy = "1.24.3"
tqdm = "^4.66.2"
tensorflow = {version = "2.16.1", extras = ["and-cuda"]}
scikit-learn = ">=1.2.2"
scikit-multilearn = "^0.2.0"
torch = {version = "<=2.0.0", source = "pytorch" }
torchvision = {version = "<=0.16.0", source = "pytorch" }
torchaudio = {version = "<=2.0.0", source = "pytorch" }
essentia-tensorflow = "2.1b6.dev1110"


[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"


[tool.poetry.group.dev.dependencies]
ipykernel = "6.19.3"
jupyterlab = "3.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
